name: Build Geode Mod

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build Android Mod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Geode
        uses: geode-sdk/setup-geode@main
        with:
          version: v3.0.0

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          platform: android
