name: Build Geode Mod

on: [push, workflow_dispatch]

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Build Android Mod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          platform: android
          setup-sdk: true
          # Pakotetaan kääntäjä tallentamaan valmis tiedosto suoraan tähän kansioon:
          output-path: ./output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-build
          # Haetaan tiedosto sieltä, minne se äsken pakotettiin
          path: ./output/*.geode
